name: PR Selective Tests

on:
  pull_request:
    branches: ["**"]
  pull_request_target:
    branches: ["**"]

# Note: pull_request_target runs with elevated permissions on the base repo.
# We do not checkout or run code from the PR in that context without sandboxing.

jobs:
  selective-tests:
    runs-on: ubuntu-latest
    env:
      LLM_MODE: mock
      CONFIDENCE_THRESHOLD: 0.6
      EXTRA_GRADLE_ARGS: ''
      SELECTOR_URL: http://localhost:8000/select-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle (for wrapper bootstrap)
        run: sudo apt-get update && sudo apt-get install -y gradle

      # Use Gradle Wrapper shipped with repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install selector service deps
        run: |
          python -m pip install --upgrade pip
          pip install -r selector-service/requirements.txt

      - name: Launch selector service
        run: |
          nohup python -m uvicorn app.main:app --app-dir selector-service --host 0.0.0.0 --port 8000 &
          sleep 3

      - name: Build Gradle project
        run: ./gradlew assemble --no-daemon

      - name: Run selector orchestrator
        run: |
          BASE_REF=${{ github.base_ref || 'main' }}
          bash tools/run_selector.sh --project-root . --base origin/${BASE_REF} --head HEAD

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selector-results
          path: |
            selector_output.json
            tools/output/

      - name: Comment results (optional)
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Selected tests run report:
            Confidence: See selector_output.json

